networks:
  backend-challenge-network:
    name: backend-challenge-network

services:
  backend-challenge-postgres-service:
    container_name: backend-challenge-postgres-service
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: backend-challenge-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PIh4Yrv75BLP1SuXY9XU
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d backend-challenge-database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      backend-challenge-network:
        aliases:
          - backend-challenge-network.challenge
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend-challenge:
    container_name: backend-challenge-backend
    depends_on:
      backend-challenge-postgres-service:
        condition: service_healthy
    image: 'wevertonsilvasouza/backend-challenge-hml:latest'
    networks:
      backend-challenge-network:
        aliases:
          - backend-challenge-network.challenge
    ports:
      - '8080:8080'
    restart: unless-stopped
